name: DeploySimpleWorkflow2
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
    - uses: azure/appservice-settings@v1
      with:
        app-name: 'LA-STD-VA'
        app-settings-json: '${{ secrets.APP_SETTINGS }}'
      
