name: DeployAppSettings
on:
  workflow_call:
    inputs:
      environmentType:
        required: false
        type: string
      resourceGroupName:
        required: false
        type: string
      appName:
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true
      APP_SETTINGS:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true
    - uses: azure/appservice-settings@v1
      with: 
         app-name: ${{ inputs.appName }}
         app-settings-json: ${{ secrets.APP_SETTINGS }}
