# This is a basic workflow to help you get started with Actions

name: Create a Logic App

# Controls when the action will run. 
on:
 workflow_dispatch:
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/arm-deploy@v1
        with:
          subscriptionId: DataResources
          resourceGroupName: 745d813b-e235-4d79-b5b5-4ebfa9fe6be4
          template: ./ARMTemplates/LA_Standard_Basic.json
          parameters: ./ARMTemplates/LA_Standard_Basic_Param.json
