name: DeployWorkflows

on:
  workflow_call:
    inputs:
      environmentType:
        required: false
        type: string
      resourceGroupName:
        required: false
        type: string
      appName:
        required: true
        type: string
    secrets:
      creds:
        required: true
      publishProfile:
        required: true


jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Easy Zip Files
        uses: vimtor/action-zip@v1
        with:
          dest: ${{ github.run_id }}.zip
          files: ./workflows
      - uses: actions/upload-artifact@master
        with:
          name: build-artifact
          path: ${{ github.run_id }}.zip
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [Build] 
    steps:
     - uses: azure/login@v1
       with:
        creds: ${{secrets.creds}}
        enable-AzPSSession: true

     - uses: actions/download-artifact@master
       with:
        name: build-artifact
        path: build-art/

     - name: Deploy to Azure Logic App1
       uses: azure/arm-deploy@v1
       with:
        scope: resourcegroup
        subscriptionId: 745d813b-e235-4d79-b5b5-4ebfa9fe6be4
        resourceGroupName: DataResources        
        template: ./workflows/stateful1/wokflow.json
        
     - name: Deploy to Azure Logic App2
       uses: azure/arm-deploy@v1
       with:
        scope: resourcegroup
        resourceGroupName: DataResources
        subscriptionId: 745d813b-e235-4d79-b5b5-4ebfa9fe6be4
        template: ./workflows/workflow1/wokflow.json

     - name: Deploy to Azure Logic Conn
       uses: azure/arm-deploy@v1
       with:
        scope: resourcegroup
        resourceGroupName: DataResources
        subscriptionId: 745d813b-e235-4d79-b5b5-4ebfa9fe6be4
        template: ./workflows/connections.json
