name: DeployWorkflows

on:
  workflow_call:
    inputs:
      environmentType:
        required: false
        type: string
      resourceGroupName:
        required: false
        type: string
      appName:
        required: true
        type: string
    secrets:
      creds:
        required: true
      publishProfile:
        required: true


jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Easy Zip Files
        uses: vimtor/action-zip@v1
        with:
          dest: ${{ github.run_id }}.zip
          files: ./workflows
      - uses: actions/upload-artifact@master
        with:
          name: build-artifact
          path: ${{ github.run_id }}.zip
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [Build] 
    steps:
     - uses: azure/login@v1
       with:
        creds: ${{secrets.creds}}
        enable-AzPSSession: true

     - uses: actions/download-artifact@master
       with:
        name: build-artifact
        path: build-art/

     - name: artifact folders
       run: |
            ls -la ${{github.wokspace}}
     - name: artifact folders
       run: |
            ls -la build-art/
            
     - name: Deploy to Azure Logic App
       uses: Azure/functions-action@v1.5.1
       with:
        app-name: LA-STD-VO
        package: build-art/${{ github.run_id }}.zip
        publish-profile: ${{ secrets.publishProfile }}
