name: deploy-logicapp

on:
  push:
    branches:
      - feature/CLI
  workflow_dispatch:

permissions:
  id-token: write
  contents: read




jobs:
  #Deploy LA to the dev environment
  deploy-LA-dev:
    uses: ./.github/workflows/deployWorkflow.yml
    with:
      environmentType: dev
      resourceGroupName: DataResources
      appName: LA-STD-VA
    secrets: 
      creds: ${{secrets.AZURE_CREDENTIALS}}
      publishProfile: ${{ secrets.AZURE_LOGICAPP_PUBLISH_PROFILE }}      
  #Deploy LA-App Settings to the dev environment
  deploy-APPSettings-dev:
    uses: ./.github/workflows/configureAppSettings.yml
    with:
      environmentType: dev
      resourceGroupName: DataResources
      appName: LA-STD-VA
    secrets: 
      creds: ${{secrets.AZURE_CREDENTIALS}}
      appSettings: ${{ secrets.APP_SETTINGS }}
