name: deploy-logicapp

on:
  push:
    branches:
      - feature/NewLogicApp
  workflow_dispatch:

permissions:
  id-token: write
  contents: read




jobs:
  #Deploy LA to the dev environment
  deploy-LA-dev:
    uses: ./.github/workflows/deployWorkflow.yml
    with:
      environmentType: dev
      resourceGroupName: DataResources
      appName: LA-STD-VO
    secrets: 
      creds: ${{secrets.AZURE_CREDENTIALS}}
      publishProfile: ${{ secrets.AZ_LA_PP }}
