name: deploy-test-LA

on:
  workflow_dispatch:
  

permissions:
  id-token: write
  contents: read


jobs:
  #Deploy to the dev environment
  deploy-dev:
    uses: ./.github/workflows/deploy.yml
    with:
      resourceGroupName: rg-vo-gpp-logicapp-dev-weu-001
      azureSubscription: sub-lz-gpp-dev-001
      serviceConnection: sub-lz-gpp-dev-001
      appName: stdlogapp-vo-gpp-dev-weu-001
      subscriptionId: 5159bd03-b515-48ea-a32f-55ef5ea3f19b
    secrets: 
      AZURE_CREDENTIALS : ${{ secrets.AZURE_CREDENTIALS }}  
