name: deploy-VanOord-LA

on:
  workflow_dispatch:
  

permissions:
  id-token: write
  contents: read


jobs:
  #Deploy to the dev environment
  deploy-dev:
    uses: ./.github/workflows/deploy.yml
    with:
      resourceGroupName: DataResources
      appName: vscodelogicapp1
      subscriptionId: 745d813b-e235-4d79-b5b5-4ebfa9fe6be4
    secrets: 
      AZURE_CREDENTIALS : ${{ secrets.AZURE_CREDENTIALS }}  
