name: deploy-test-LA

on:
  push:
    branches: main
  workflow_dispatch:
  

permissions:
  id-token: write
  contents: read


jobs:
  #Deploy to the dev environment
  login:
    runs-on: ubuntu-latest
    steps:
     - name: Azure Login
       uses: azure/login@v1
       with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
